services:
  # ----------------------------------- APPS
  chemnitz-map-client:
    container_name: chemnitz-map-client
    build:
      context: .
      dockerfile: Dockerfile.Dev
    ports:
      - 3000:3000
    env_file:
      - .env
