global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'chemnitz_maps_dev'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:80']

  - job_name: 'chemnitz_maps_prod'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['chemnitz_map_server:80']
